sudo: required

services: docker

language: generic

before_install:
  - sudo apt-get update
  - sudo apt-get -qqy -o Dpkg::Options::="--force-confdef" -o Dpkg::Options::="--force-confold" install docker-engine
  - sudo service docker restart

script: |-
   docker build -t jbaruch-docker.jfrog.io/couchbase-javaee:$TRAVIS_BUILD_NUMBER . \
   && echo 'Pushing Docker image to Artifactory' \
   && docker login -u $ARTIFACTORY_USER -p $ARTIFACTORY_API_KEY jbaruch-docker.jfrog.io \
   && docker push jbaruch-docker.jfrog.io/couchbase-javaee:$TRAVIS_BUILD_NUMBER \
   && echo 'Docker image pushed to Artifactory' \
   && echo 'Alliasing the Docker image as latest' \
   && curl -i -u $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY -H "Content-Type:application/json" -X POST https://jbaruch.jfrog.io/jbaruch/api/docker/docker-dev-local/v2/promote -d '{"dockerRepository": "couchbase-javaee","tag": "'$TRAVIS_BUILD_NUMBER'","targetRepo": "docker-dev-local","targetTag": "latest","copy":true}' \
   && echo 'latest tag created' \
   && echo 'Creating propery in latest to actual version number' \
   && curl -i -u $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY -X PUT https://jbaruch.jfrog.io/jbaruch/api/storage/docker-dev-local/couchbase-javaee/latest?properties=artifactory.refersToVersion=$TRAVIS_BUILD_NUMBER \
   && echo 'artifactory.refersTo property created' \
   && if [ -n "$JAVA_BUILD_NUMBER" ]; then echo 'Promoting Java build' \
   && curl -i -u $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY -H "Content-Type:application/json" -X POST https://jbaruch.jfrog.io/jbaruch/api/build/promote/couchbase-javaee/$JAVA_BUILD_NUMBER -d '{"status": "contained","comment" : "This build contained in Docker tag couchbase-javaee:'$TRAVIS_BUILD_NUMBER'","ciUser": "'$USER'"}' \
   && echo 'Java build promoted to "Contained" status" \
   && echo 'Adding Java build number property to the Docker image' \
   && curl -i -u $ARTIFACTORY_USER:$ARTIFACTORY_API_KEY -X PUT "https://jbaruch.jfrog.io/jbaruch/api/storage/docker-dev-local/couchbase-javaee/$TRAVIS_BUILD_NUMBER?properties=build.containsWarBuildName=couchbase-javaee|build.containsWarBuildNumber=$JAVA_BUILD_NUMBER" \
   && echo '"build.containsWarBuildName" property added'; fi
